apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.env }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.externalSecrets.enabled }}
        # Garante restart se a definição do ExternalSecret mudar
        checksum/secret: {{ include (print $.Template.BasePath "/external-secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "generic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "generic.containerName" . }}
          image: "{{ required "image.repository é obrigatório" .Values.image.repository }}:{{ required "image.tag é obrigatório" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          {{- if or .Values.env .Values.externalSecrets.enabled }}
          envFrom:
            {{- if .Values.env }}
            - configMapRef:
                name: {{ include "generic.fullname" . }}
            {{- end }}
            {{- if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ include "generic.fullname" . }}-secret
            {{- end }}
          {{- end }}