nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

container:
  name: ""
  port: 3000

resources: {}
  # requests:
  #   cpu: 500m
  #   memory: 512Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  nameSuffix: ingress
  className: ""   # ex: alb (campo spec.ingressClassName)
  commonAnnotations: {}
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  pollingInterval: 30
  cooldownPeriod: 300
  triggers: []
  # Exemplo de trigger:
  # - type: cpu
  #   metadata:
  #     type: Utilization
  #     value: "50"

env: {}
  # LOG_LEVEL: "debug"
  # API_URL: "https://api.exemplo.com"

externalSecrets:
  enabled: false
  # Nome da secret no AWS Secrets Manager (ex: dev/app-x)
  # Se n√£o definido, tenta usar o fullname do chart.
  awsSecretName: ""
  secretStoreRef:
    name: "aws-secrets-manager"
    kind: ClusterSecretStore

# Annotations para serem injetadas especificamente na spec do POD
podAnnotations: {}

opentelemetry:
  enabled: false
  type: java
  endpoint: "http://otel-collector.monitoring.svc:4317"
  samplerRatio: "1.0"
  images:
    nodejs: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest"
    java: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest"
    python: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest"
    dotnet: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest"
